//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FletnixDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cast
    {
        public int TitleID { get; set; }
        public int CastMemberID { get; set; }
        public string Role { get; set; }
    
        public virtual CastMember CastMember { get; set; }
        public virtual Role Role1 { get; set; }
        public virtual Title Title { get; set; }
    }
}
