//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FletnixDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.Movie1 = new HashSet<Movie>();
            this.Genre = new HashSet<Genre>();
        }
    
        public int TitleID { get; set; }
        public Nullable<int> SequelOf_TitleID { get; set; }
    
        public virtual ICollection<Movie> Movie1 { get; set; }
        public virtual Movie Movie2 { get; set; }
        public virtual Title Title { get; set; }
        public virtual ICollection<Genre> Genre { get; set; }
    }
}
