//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FletnixDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewRating
    {
        public int TitleReview_TitleID { get; set; }
        public int TitleReview_UserID { get; set; }
        public int UserID { get; set; }
        public byte Rating { get; set; }
    
        public virtual TitleReview TitleReview { get; set; }
        public virtual User User { get; set; }
    }
}
