//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FletnixDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public Title()
        {
            this.Cast = new HashSet<Cast>();
            this.PurchaseHistory = new HashSet<PurchaseHistory>();
            this.TitleReview = new HashSet<TitleReview>();
            this.WatchHistory = new HashSet<WatchHistory>();
            this.Keyword = new HashSet<Keyword>();
        }
    
        public int TitleID { get; set; }
        public string Title1 { get; set; }
        public decimal Price { get; set; }
        public bool IsWatchable { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public decimal DiscountPercentage { get; set; }
        public Nullable<decimal> AverageRating { get; set; }
        public string ImageLocation { get; set; }
        public string VideoLocation { get; set; }
    
        public virtual ICollection<Cast> Cast { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual ICollection<PurchaseHistory> PurchaseHistory { get; set; }
        public virtual ICollection<TitleReview> TitleReview { get; set; }
        public virtual TvEpisode TvEpisode { get; set; }
        public virtual ICollection<WatchHistory> WatchHistory { get; set; }
        public virtual ICollection<Keyword> Keyword { get; set; }
    }
}
