//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FletnixDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TvEpisode
    {
        public int TitleID { get; set; }
        public int SeriesID { get; set; }
        public int SeasonNr { get; set; }
        public int EpisodeNr { get; set; }
    
        public virtual Season Season { get; set; }
        public virtual Title Title { get; set; }
    }
}
