//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FletnixDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.PurchaseHistory = new HashSet<PurchaseHistory>();
            this.ReviewRating = new HashSet<ReviewRating>();
            this.TitleReview = new HashSet<TitleReview>();
            this.WatchHistory = new HashSet<WatchHistory>();
        }
    
        public int UserID { get; set; }
        public string UserType { get; set; }
        public string CountryCode { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Username { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string BankAccountNumber { get; set; }
        public string PasswordSalt { get; set; }
        public bool IsVerified { get; set; }
        public string VerificationToken { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<PurchaseHistory> PurchaseHistory { get; set; }
        public virtual ICollection<ReviewRating> ReviewRating { get; set; }
        public virtual ICollection<TitleReview> TitleReview { get; set; }
        public virtual UserType UserType1 { get; set; }
        public virtual ICollection<WatchHistory> WatchHistory { get; set; }
    }
}
